### ISSUE TITLE
Where can I get that cool Data-over-Powerline library?

### ISSUE THREAD

**Issue by drawkula** [SensorsIot/RFLink-MQTT-Gateway#1]
[Diagram.JPG](https://github.com/SensorsIot/RFLink-MQTT-Gateway/blob/a2e95905ff9ea1c9daaf80cbe5e74dfd854b2eec/Diagram.JPG) shows data and power using the same pin.

**Comment by michalszymura** [comment]
obviously it's just a simple mistake, but if you want data over power look into 1-wire devices

**Comment by drawkula** [comment]
> obviously it's just a simple mistake, but if you want data over power look into 1-wire devices

Obviously a simple mistake was my attempt to report this with a wink.
