### ISSUE TITLE
issue in code

### ISSUE THREAD

**Issue by draakje111** [SensorsIot/RFLink-MQTT-Gateway#2]
Hi Sensorslot,

I was interested in your project and found some small issue in your code. Specifically the connecting to the broker is not working for me. The reason is that you don't connect via user and password probably it works for you that way. 

On line 93 you have placed the clossing brakked at the wrong place
yours ->  if (client.connect(clientId.c_str()), MQTT_USER, MQTT_PASSWORD)
corrected one ->    if (client.connect(clientId.c_str(), MQTT_USER, MQTT_PASSWORD))

as you can see it is not using the user and password in the client.connect function ;). I got it working after placing the closing bracket at the correct place.

Further question, do you have plans also sending RF signals over your gateway? I'm using rflink to control some ligths in house.

**Comment by SensorsIot** [comment]
Thank you!
